openapi: 3.0.1
info:
  title: BuscaDadosBeneficiario
  description: API Definition of BuscaDadosBeneficiario
  version: 1.0.0
servers:
- url: http://localhost:8290/buscadadosbeneficiario
paths:
  /:
    get:
      responses:
        default:
          description: Default response
